##########################################################################################
### Config file for running PlotRocCurvesWithAuc.r
##########################################################################################

# input file(s) containing list of [met set score, binary membership label] for known mets
#	tab-delimited file with headers: Score, Label
#	generated by "GenerateRocCurveData.py"
#	(can add more files to list to compare different annotation matrices)
dataFiles <- c("example_data_1_SignalMetSetAnnotationMatrix_2Mets_top10MCs_confidentSets_rocData.txt")

# number of MCs used to generate met set scores/annotation matrix
#	(can add more values to list to compare different annotation matrices)
nMCs <- c(10)

# output file (PDF) containing plot of ROC curve and AUC
outFile <- "example_data_1_SignalMetSetAnnotationMatrix_2Mets_top10MCs_confidentSets_ROC-AUC.pdf"

